name: Build SACD-Ripper PKG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          build-essential autoconf automake bison flex libtool libtool-bin pkg-config \
          libgmp-dev libmpfr-dev libmpc-dev libelf-dev zlib1g-dev \
          python3 python3-dev python-is-python3 python3-distutils \
          texinfo wget git bzip2 libncurses-dev m4

    - name: Build PS3 toolchain
      run: |
        export PS3DEV="$HOME/ps3dev"
        export PSL1GHT="$PS3DEV"
        export PATH="$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin:$PATH"
        mkdir -p "$PS3DEV"
        git clone https://github.com/ps3dev/ps3toolchain.git
        cd ps3toolchain
        ./toolchain.sh

    - name: Install PSL1GHT
      run: |
        export PS3DEV="$HOME/ps3dev"
        export PSL1GHT="$PS3DEV"
        export PATH="$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin:$PATH"
        git clone https://github.com/PS3Dev/PSL1GHT.git
        cd PSL1GHT
        make install-ctrl
        make
        make install

    - name: Build SACD-Ripper PKG
      run: |
        export PS3DEV="$HOME/ps3dev"
        export PSL1GHT="$PS3DEV"
        export PATH="$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin:$PATH"
        git clone https://github.com/EuFlo/sacd-ripper.git
        cd sacd-ripper
        make ps3_pkg

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SACD_Ripper.pkg
        path: sacd-ripper/pkg/SACD_Ripper.pkg
