name: Build PS3 PKG (manual)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build SACD-Ripper PKG
        run: |
          docker run --rm -v "${{ github.workspace }}":/workspace \
            docker.io/ps3dev/ps3toolchain:latest \
            make ps3_pkg

      - name: Upload PKG
        uses: actions/upload-artifact@v4
        with:
          name: SACD_Ripper_v0.40_fix5_(HEN).pkg
          path: pkg/SACD_Ripper.pkg
