name: Build SACD-Ripper PKG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install all build dependencies
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          build-essential autoconf automake bison flex libtool libtool-bin pkg-config \
          gawk m4 \
          libgmp-dev libmpfr-dev libmpc-dev libelf-dev zlib1g-dev \
          python2-dev python3 python3-dev python-is-python3 python3-distutils \
          texinfo wget git bzip2 libncurses-dev

        # Ensure PS3Toolchain sees python-config
        sudo ln -sf "$(which python3-config)" /usr/bin/python-config

    - name: Build PS3 toolchain
      run: |
        export PS3DEV="$HOME/ps3dev"
        export PSL1GHT="$PS3DEV"
        export PATH="$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin:$PATH"
        mkdir -p "$PS3DEV"
        git clone https://github.com/ps3dev/ps3toolchain.git
        cd ps3toolchain
        ./toolchain.sh

    - name: Install PSL1GHT
      run: |
        export PS3DEV="$HOME/ps3dev"
        export PSL1GHT="$PS3DEV"
        export PATH="$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin:$PATH"
        git clone https://github.com/PS3Dev/PSL1GHT.git
        cd PSL1GHT
        make install-ctrl
        make
        make install

    - name: Build SACD-Ripper PKG
      run: |
        export PS3DEV="$HOME/ps3dev"
        export PSL1GHT="$PS3DEV"
        export PATH="$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin:$PATH"

        # Clone upstream sacd-ripper with submodules so all PS3 libraries are included
        git clone --depth=1 --branch 0.3.9.3 --recursive \
          https://github.com/sacd-ripper/sacd-ripper.git sacd-ripper
        cd sacd-ripper

        # Build all libraries and ELF
        make clean
        make

        # Package into PS3 .pkg
        make sacd-ripper.pkg

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SACD_Ripper.pkg
        path: sacd-ripper.pkg
